name: Add Agent to Directory
description: Submit a new agent or update existing agent information
title: "[Agent]: "
labels: ["agent-submission", "needs-review"]
body:
- type: markdown
  attributes:
  value: |
  Thanks for taking the time to submit or update an agent!
- type: dropdown
  id: submission-type
  attributes:
  label: Type of Submission
  options: - New Agent Submission - Update Existing Agent
  description: Are you adding a new agent or updating an existing one?
  validations:
  required: true

- type: input
  id: agent-name
  attributes:
  label: agent Name
  description: Name of the agent/agent
  placeholder: MyAwesomeAgent
  validations:
  required: true

- type: input
  id: twitter
  attributes:
  label: Twitter Username
  description: Twitter handle associated with the agent
  placeholder: "@agentname"

- type: input
  id: framework
  attributes:
  label: Framework
  description: Main framework or technology used
  placeholder: "eliza, bespoke, fatduck, etc."
  validations:
  required: true

- type: input
  id: github-source
  attributes:
  label: GitHub Source Link
  description: Link to the agent's GitHub repository
  placeholder: https://github.com/username/repo
  validations:
  required: true

- type: input
  id: developer
  attributes:
  label: Developer/Organization
  description: Who created/maintains this agent?
  placeholder: "Developer Name or Organization"
  validations:
  required: true

- type: input
  id: character-file
  attributes:
  label: Character File
  description: Link to the agent's character/personality definition file
  placeholder: https://github.com/username/repo/blob/main/character.txt
  validations:
  required: true

- type: textarea
  id: description
  attributes:
  label: Description
  description: What does your agent do? What makes it special?
  placeholder: Describe the agent's main features and capabilities...
  validations:
  required: true

- type: checkboxes
  id: terms
  attributes:
  label: Submission Requirements
  description: Please confirm the following
  options: - label: I have added/updated the agent in the main table in README.md
  required: true - label: This agent does not promote or enable illegal activities
  required: true - label: All provided links are valid and accessible
  required: true - label: The information provided is accurate and up-to-date
  required: true
